import type { Category, Note, NoteRelation, Tag } from './types';

export const categories: Category[] = [
  { id: 'development', name: 'Development', color: '#79a8ff' },
  { id: 'design', name: 'Design', color: '#e48cff' },
  { id: 'personal', name: 'Personal', color: '#65dcc0' },
];

export const tags: Tag[] = [
  { id: 'web', name: 'Web' },
  { id: 'learning', name: 'Learning' },
  { id: 'idea', name: 'Idea' },
  { id: 'systems', name: 'Systems' },
];

const note = (
  id: string,
  title: string,
  categoryId: string,
  parentNoteId: string | null,
  tagIds: string[],
): Note => ({
  id,
  title,
  categoryId,
  parentNoteId,
  tagIds,
  content: `${title}에 대한 연결된 생각과 참고 노트입니다.`,
});

export const notes: Note[] = [
  note('programming', 'Programming', 'development', null, ['learning']),
  note('frontend', 'Frontend', 'development', 'programming', ['web']),
  note('react', 'React', 'development', 'frontend', ['web', 'learning']),
  note('hooks', 'Hooks', 'development', 'react', ['learning']),
  note('use-state', 'useState', 'development', 'hooks', ['learning']),
  note('use-effect', 'useEffect', 'development', 'hooks', ['learning']),
  note('state-management', 'State Management', 'development', 'react', [
    'systems',
  ]),
  note('zustand', 'Zustand', 'development', 'state-management', ['systems']),
  note('three-js', 'Three.js', 'development', 'frontend', ['web']),
  note('webgl', 'WebGL', 'development', 'three-js', ['web']),
  note('backend', 'Backend', 'development', 'programming', ['systems']),
  note('database', 'Database', 'development', 'backend', ['systems']),
  note('authentication', 'Authentication', 'development', 'backend', ['web']),
  note('design-system', 'Design System', 'design', null, ['systems']),
  note('typography', 'Typography', 'design', 'design-system', ['idea']),
  note('motion', 'Motion', 'design', 'design-system', ['idea']),
  note('knowledge', 'Knowledge Garden', 'personal', null, ['idea']),
  note('weekly-review', 'Weekly Review', 'personal', 'knowledge', ['learning']),
  note('reading', 'Reading Notes', 'personal', 'knowledge', ['learning']),
  note('ideas', 'Side Project Ideas', 'personal', 'knowledge', ['idea']),
  note('testing', 'Testing', 'development', 'frontend', ['learning']),
  note('vitest', 'Vitest', 'development', 'testing', ['learning']),
  note('component-api', 'Component API', 'development', 'frontend', ['web']),
  note('accessibility', 'Accessibility', 'development', 'frontend', ['web']),
  note('performance', 'Performance', 'development', 'frontend', ['systems']),
  note('vite', 'Vite', 'development', 'programming', ['web']),
  note('typescript', 'TypeScript', 'development', 'programming', ['learning']),
  note('api-design', 'API Design', 'development', 'backend', ['systems']),
  note('rest', 'REST', 'development', 'api-design', ['web']),
  note('caching', 'Caching', 'development', 'backend', ['systems']),
  note('visual-language', 'Visual Language', 'design', 'design-system', [
    'idea',
  ]),
  note('color', 'Color', 'design', 'visual-language', ['idea']),
  note('spacing', 'Spacing', 'design', 'visual-language', ['idea']),
  note('layout', 'Layout', 'design', 'visual-language', ['web']),
  note('interaction', 'Interaction', 'design', 'motion', ['idea']),
  note('micro-interactions', 'Micro-interactions', 'design', 'interaction', [
    'idea',
  ]),
  note('transitions', 'Transitions', 'design', 'interaction', ['idea']),
  note('research', 'Research', 'design', null, ['learning']),
  note('user-interviews', 'User Interviews', 'design', 'research', [
    'learning',
  ]),
  note('prototypes', 'Prototypes', 'design', 'research', ['idea']),
  note('personal-systems', 'Personal Systems', 'personal', null, ['systems']),
  note('habits', 'Habits', 'personal', 'personal-systems', ['learning']),
  note('capture', 'Capture', 'personal', 'personal-systems', ['idea']),
  note('projects', 'Projects', 'personal', 'knowledge', ['idea']),
  note('orbit-concept', 'Orbit Concept', 'personal', 'projects', ['idea']),
  note('planning', 'Planning', 'personal', 'projects', ['systems']),
  note('goals', 'Goals', 'personal', 'planning', ['learning']),
  note('journal', 'Journal', 'personal', 'knowledge', ['learning']),
  note('reflections', 'Reflections', 'personal', 'journal', ['learning']),
  note('year-2026', '2026 Notes', 'personal', 'weekly-review', ['learning']),
  note('week-34', 'Week 34', 'personal', 'weekly-review', ['learning']),
  note('cli-tools', 'CLI Tools', 'development', 'programming', ['systems']),
  note('deployment', 'Deployment', 'development', 'backend', ['web']),
  note('observability', 'Observability', 'development', 'backend', ['systems']),
  note('wireframes', 'Wireframes', 'design', 'prototypes', ['idea']),
  note('content-design', 'Content Design', 'design', 'design-system', ['web']),
  note('focus', 'Focus', 'personal', 'personal-systems', ['learning']),
  note('routines', 'Routines', 'personal', 'habits', ['learning']),
  note('experiments', 'Experiments', 'personal', 'projects', ['idea']),
  note('bookmarks', 'Bookmarks', 'personal', 'knowledge', ['web']),
];

export const relations: NoteRelation[] = [
  {
    id: 'r1',
    sourceNoteId: 'react',
    targetNoteId: 'three-js',
    relationType: 'related',
  },
  {
    id: 'r2',
    sourceNoteId: 'zustand',
    targetNoteId: 'react',
    relationType: 'related',
  },
  {
    id: 'r3',
    sourceNoteId: 'webgl',
    targetNoteId: 'motion',
    relationType: 'related',
  },
  {
    id: 'r4',
    sourceNoteId: 'design-system',
    targetNoteId: 'frontend',
    relationType: 'related',
  },
  {
    id: 'r5',
    sourceNoteId: 'authentication',
    targetNoteId: 'database',
    relationType: 'related',
  },
  {
    id: 'r6',
    sourceNoteId: 'reading',
    targetNoteId: 'knowledge',
    relationType: 'related',
  },
  {
    id: 'r7',
    sourceNoteId: 'ideas',
    targetNoteId: 'weekly-review',
    relationType: 'related',
  },
  {
    id: 'r8',
    sourceNoteId: 'vitest',
    targetNoteId: 'react',
    relationType: 'related',
  },
  {
    id: 'r9',
    sourceNoteId: 'accessibility',
    targetNoteId: 'design-system',
    relationType: 'related',
  },
  {
    id: 'r10',
    sourceNoteId: 'performance',
    targetNoteId: 'webgl',
    relationType: 'related',
  },
  {
    id: 'r11',
    sourceNoteId: 'typescript',
    targetNoteId: 'zustand',
    relationType: 'related',
  },
  {
    id: 'r12',
    sourceNoteId: 'rest',
    targetNoteId: 'authentication',
    relationType: 'related',
  },
  {
    id: 'r13',
    sourceNoteId: 'caching',
    targetNoteId: 'database',
    relationType: 'related',
  },
  {
    id: 'r14',
    sourceNoteId: 'color',
    targetNoteId: 'typography',
    relationType: 'related',
  },
  {
    id: 'r15',
    sourceNoteId: 'layout',
    targetNoteId: 'component-api',
    relationType: 'related',
  },
  {
    id: 'r16',
    sourceNoteId: 'micro-interactions',
    targetNoteId: 'three-js',
    relationType: 'related',
  },
  {
    id: 'r17',
    sourceNoteId: 'user-interviews',
    targetNoteId: 'weekly-review',
    relationType: 'related',
  },
  {
    id: 'r18',
    sourceNoteId: 'orbit-concept',
    targetNoteId: 'three-js',
    relationType: 'related',
  },
  {
    id: 'r19',
    sourceNoteId: 'planning',
    targetNoteId: 'personal-systems',
    relationType: 'related',
  },
  {
    id: 'r20',
    sourceNoteId: 'reflections',
    targetNoteId: 'reading',
    relationType: 'related',
  },
  {
    id: 'r21',
    sourceNoteId: 'deployment',
    targetNoteId: 'observability',
    relationType: 'related',
  },
  {
    id: 'r22',
    sourceNoteId: 'wireframes',
    targetNoteId: 'prototypes',
    relationType: 'related',
  },
  {
    id: 'r23',
    sourceNoteId: 'content-design',
    targetNoteId: 'accessibility',
    relationType: 'related',
  },
  {
    id: 'r24',
    sourceNoteId: 'routines',
    targetNoteId: 'focus',
    relationType: 'related',
  },
  {
    id: 'r25',
    sourceNoteId: 'experiments',
    targetNoteId: 'ideas',
    relationType: 'related',
  },
];
